function [fitresult, gof] = fitcalibration2data(gyrorate, gyrotemps, rigrates)
%CREATEFIT(GYRORATE,GYROTEMPS,RIGRATES)
%  Create a fit.
%
%  Data for 'Gyro Data Fit' fit:
%      X Input: gyrorate
%      Y Input: gyrotemps
%      Z Output: rigrates
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-Oct-2024 19:39:18


%% Fit: 'Gyro Data Fit'.
[xData, yData, zData] = prepareSurfaceData( gyrorate, gyrotemps, rigrates );

% Set up fittype and options.
ft = fittype( 'a+b*x^3+c*x*y+d*cos(f*x-1.571)', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.MaxFunEvals = 500000;
opts.MaxIter = 500000;
opts.Robust = 'Bisquare';
opts.StartPoint = [0.910647594429523 0.181847028302852 0.26380291652199 0.145538980384717 0.136068558708664];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'Gyro Data Fit' );

% Plot fit with data.
subplot( 2, 1, 1 );
plot( fitresult, [xData, yData], zData );
% Label axes
xlabel( 'gyrorate', 'Interpreter', 'none' );
ylabel( 'gyrotemps', 'Interpreter', 'none' );
zlabel( 'rigrates', 'Interpreter', 'none' );
grid on
view( 17.4, 46.9 );

% Plot residuals.
subplot( 2, 1, 2 );
plot( fitresult, [xData, yData], zData, 'Style', 'Residual' );
% Label axes
xlabel( 'gyrorate', 'Interpreter', 'none' );
ylabel( 'gyrotemps', 'Interpreter', 'none' );
zlabel( 'rigrates', 'Interpreter', 'none' );
grid on
view( 17.4, 46.9 );


