function [fitresult, gof] = fitcalibration2data(gyrorates, gyrotemps, rigrates)
%CREATEFIT(GYRORATES,GYROTEMPS,RIGRATES)
%  Create a fit.
%
%  Data for 'Gyro Data Fit' fit:
%      X Input: gyrorates
%      Y Input: gyrotemps
%      Z Output: rigrates
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Aug-2024 00:51:13


%% Fit: 'Gyro Data Fit'.
[xData, yData, zData] = prepareSurfaceData( gyrorates, gyrotemps, rigrates );

% Set up fittype and options.
ft = fittype( 'a+b*x+c*x*y+d*cos(f*x+g)', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.MaxFunEvals = 500000;
opts.MaxIter = 500000;
opts.Robust = 'Bisquare';
opts.StartPoint = [0.0286741524641061 0.489901388512224 0.167927145682257 0.500471624154843 0.471088374541939 0.0596188675796392];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'Gyro Data Fit' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'Gyro Data Fit', 'rigrates vs. gyrorates, gyrotemps', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'gyrorates', 'Interpreter', 'none' );
ylabel( 'gyrotemps', 'Interpreter', 'none' );
zlabel( 'rigrates', 'Interpreter', 'none' );
grid on
view( 26.2, -14.8 );

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, [xData, yData], zData, 'Style', 'Residual' );
legend( h, 'Gyro Data Fit - residuals', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'gyrorates', 'Interpreter', 'none' );
ylabel( 'gyrotemps', 'Interpreter', 'none' );
zlabel( 'rigrates', 'Interpreter', 'none' );
grid on
view( 26.2, -14.8 );


